projects:
  ycuschedule:
    schemaPath: amplify/backend/api/ycuschedule/build/schema.graphql
    includes:
      - web/src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: web/src/API.ts
        docsFilePath: web/src/graphql
        region: ap-northeast-1
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
