name: check-web-pr

on:
  pull_request:
    branches:
      - main
    paths:
      - web/**/*

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - uses: actions/cache@v2
        with:
          path: 'web/**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('web/**/yarn.lock') }}

      - name: install
        run: yarn

      - name: lint
        run: yarn lint-check:web

      - name: type-check
        run: yarn type-check:web

      - name: test
        run: yarn test web

      - name: build
        run: yarn workspace web build
