on:
  push:
    branches:
      - main
    tag:
      - "v*"

name: Deploy Prod to AWS

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: cache gatsby build
        uses: actions/cache@v2
        id: gatsby-cache-build
        with:
          path: |
            web/public
            web/.cache
          key: ${{ runner.os }}-gatsby-build-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-

      - name: Install Dependencies
        run: yarn

      - name: Deploy
        # run first deploy
        # run: yarn deploy--first
        run: yarn deploy:prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # - name: Notify result to slack
      #   uses: homoluctus/slatify@master
      #   if: always()
      #   with:
      #     type: ${{ job.status }}
      #     job_name: '*Deploy Lambda*'
      #   env:
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
