component: '../node_modules/@sls-next/serverless-component'
name: web

inputs:
  name: ycu-schedule-web
  domain: ycu-schedule.ycu-engine.dev
  domainType: www
  bucketName: ycu-schedule-web
  cloudfront:
    distributionId: E286RN5HQFERMV
  build:
    env:
      AZURE_CLIENT_ID: ${env.AZURE_CLIENT_ID}
      AZURE_CLIENT_SECRET: ${env.AZURE_CLIENT_SECRET}
      AZURE_TENANT_ID: ${env.AZURE_TENANT_ID}
      NEXTAUTH_URL: https://www.ycu-schedule.ycu-engine.dev
